name: stripe
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0-224.0.dev <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  stripe_platform_interface:
    path: ../stripe_platform_interface/
  stripe_ios:
    path: ../stripe_ios/
  stripe_android:
    path: ../stripe_android/  

dev_dependencies:
  flutter_test:
    sdk: flutter




