name: stripe_platform_interface
description: A new Flutter project.
version: 0.0.0+1

environment:
  sdk: ">=2.12.0-0.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0
  meta: ^1.3.0-nullsafety
  plugin_platform_interface: ^1.1.0-nullsafety
  freezed_annotation: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety
  build_runner: ^1.11.5
  json_serializable: ^4.0.1
  freezed: ^0.14.1+1

flutter: